In [34]:
from glob import glob
import pandas as pd

filepath = 'data/*.csv'
files = glob(filepath)
print(files[8])
df = pd.read_csv(files[0],encoding='utf-8')
df.head()

data\소상공인시장진흥공단_상가(상권)정보_서울_202512.csv

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220800828292,디자인바다,NaN,M1,과학·기술,M114,인쇄·제품제작,M11401,명함/간판/광고물 제작,C33910,...,4215011100112370003010826,강원일보,강원특별자치도 강릉시 성덕포남로200번길 3,210954,25487,NaN,4,NaN,128.907359,37.769424
1,MA010120220804650800,수리봉약선요리,전문점,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,4213037021102040001000001,NaN,강원특별자치도 원주시 흥업면 자재기길 65-2,220844,26403,NaN,NaN,NaN,127.923945,37.297825
2,MA010120220804643855,북스타문고,NaN,G2,소매,G213,오락용품 소매,G21301,서점,G47611,...,4213011000111200001000001,M스타,강원특별자치도 원주시 서원대로 121-1,220100,26437,NaN,2,NaN,127.926882,37.346880
3,MA010120220804528687,봄내치킨앤떡볶이,NaN,I2,음식,I210,기타 간이,I21007,김밥/만두/분식,I56193,...,4211012400108130000015171,퇴계주공뜨란채3단지,강원특별자치도 춘천시 퇴계로 220-19,200761,24392,NaN,1,NaN,127.742691,37.855030
4,MA010120220804706623,다빈치모텔,NaN,I1,숙박,I101,일반 숙박,I10102,여관/모텔,I55102,...,4215034028000500027048335,NaN,강원특별자치도 강릉시 강동면 헌화로 920-40,210824,25631,NaN,NaN,NaN,129.041861,37.682861

In [35]:
df2 = df.drop('상가업소번호', axis=1)
column_list = list(df2.columns)
result = []
for cname in df2.columns:
    if '코드' in cname:
        result.append(cname)

result
df2.drop(result, axis=1)

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,디자인바다,NaN,과학·기술,인쇄·제품제작,명함/간판/광고물 제작,간판 및 광고물 제조업,강원특별자치도,강릉시,포남1동,포남동,...,4215011100112370003010826,강원일보,강원특별자치도 강릉시 성덕포남로200번길 3,210954,25487,NaN,4,NaN,128.907359,37.769424
1,수리봉약선요리,전문점,음식,한식,백반/한정식,한식 일반 음식점업,강원특별자치도,원주시,흥업면,흥업면,...,4213037021102040001000001,NaN,강원특별자치도 원주시 흥업면 자재기길 65-2,220844,26403,NaN,NaN,NaN,127.923945,37.297825
2,북스타문고,NaN,소매,오락용품 소매,서점,서적; 신문 및 잡지류 소매업,강원특별자치도,원주시,단계동,단계동,...,4213011000111200001000001,M스타,강원특별자치도 원주시 서원대로 121-1,220100,26437,NaN,2,NaN,127.926882,37.346880
3,봄내치킨앤떡볶이,NaN,음식,기타 간이,김밥/만두/분식,치킨 전문점,강원특별자치도,춘천시,석사동,석사동,...,4211012400108130000015171,퇴계주공뜨란채3단지,강원특별자치도 춘천시 퇴계로 220-19,200761,24392,NaN,1,NaN,127.742691,37.855030
4,다빈치모텔,NaN,숙박,일반 숙박,여관/모텔,여관업,강원특별자치도,강릉시,강동면,강동면,...,4215034028000500027048335,NaN,강원특별자치도 강릉시 강동면 헌화로 920-40,210824,25631,NaN,NaN,NaN,129.041861,37.682861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107448,연가,NaN,소매,섬유·의복·신발 소매,기타 의류 소매업,기타 의복 소매업,강원특별자치도,강릉시,교2동,교동,...,4215011000101380000014011,NaN,강원특별자치도 강릉시 강릉대로 268-1,210920,25551,NaN,NaN,NaN,128.898972,37.760992
107449,프렌즈스크린,혁신점,예술·스포츠,스포츠 서비스,골프 연습장,골프 연습장 운영업,강원특별자치도,원주시,반곡관설동,반곡동,...,4213011700118990001000001,NaN,강원특별자치도 원주시 양지로 50,220170,26462,NaN,NaN,NaN,127.984134,37.326163
107450,애프터눈,NaN,수리·개인,이용·미용,미용실,이용업,강원특별자치도,원주시,무실동,단계동,...,4213011000108940001022664,NaN,강원특별자치도 원주시 이화6길 46,220939,26382,NaN,NaN,NaN,127.931632,37.341310
107451,영아미가,NaN,음식,한식,백반/한정식,한식 일반 음식점업,강원특별자치도,춘천시,신사우동,우두동,...,4211011800111050000000001,NaN,강원특별자치도 춘천시 우두1길 43,200150,24221,NaN,NaN,NaN,127.738456,37.908941
107452,소연식당,NaN,음식,한식,백반/한정식,한식 일반 음식점업,강원특별자치도,원주시,개운동,개운동,...,4213010500103820031002806,NaN,강원특별자치도 원주시 개봉교길 19,220931,26443,NaN,NaN,NaN,127.956738,37.343768

In [36]:
result = [ cname for cname in df2.colums if '코드' in cname ]

AttributeError: 'DataFrame' object has no attribute 'colums'

In [ ]:
df2.loc[:, '지번본번지':]

In [ ]:
df3['상권업종소분류명'].value_counts()