In [3]:
import pandas as pd

data = {
    'name': ['Kim', 'Lee', 'Park'],
    'age': [25, 30, 35],
    'city': ['Seoul', 'Busan', 'Incheon']
}
df = pd.DataFrame(data)
df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [5]:
data = {'name': 'Kim', 'age': 25, 'city': 'Seoul'}
s = pd.Series(data)
s

name      Kim
age        25
city    Seoul
dtype: object

In [6]:
data = [
    {'name': 'Kim', 'age': 25, 'city': 'Seoul'},
    {'name': 'Lee', 'age': 30, 'city': 'Busan'},
    {'name': 'Park', 'age': 35, 'city': 'Incheon'}
]
df = pd.DataFrame(data)
df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [13]:
data = [
    ['Kim', 25, 'Seoul'],
    ['Lee', 30, 'Busan'],
    ['Park', 35, 'Incheon']
]
df = pd.DataFrame(data, #columns=['name', 'age', 'city']
                  )
df

      0   1        2
0   Kim  25    Seoul
1   Lee  30    Busan
2  Park  35  Incheon

In [31]:
s1 = pd.Series(['Kim', 'Lee', 'Park'], name='name')
s2 = pd.Series([25, 30, 35], name='age')
df = pd.DataFrame({'name': s1, 'age': s2})
df

   name  age
0   Kim   25
1   Lee   30
2  Park   35

In [17]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
df.T

   0  1  2
A  1  4  7
B  2  5  8
C  3  6  9

In [33]:
# df.shape        # (행 수, 열 수)
# df.size         # 전체 요소 개수
# df.ndim         # 차원 (항상 2)
# df.index        # 인덱스 객체
# df.columns      # 컬럼 객체
# df.values       # NumPy 배열
# df.dtypes       # 각 컬럼의 데이터 타입

data = {
    'city' : ['서울', '대전', '대구', '부산'],
    'data1' : np.random.randint(100000, 1000000, 4),
    'data2' : np.random.randn(4)
}
df = pd.DataFrame(data)
print(df.shape) # (4, 3)
print(df.size) # 전체 요소의 개수 : 12
print(df.ndim)
print(df.index)
print(df.columns)
print(df.values)
print(df.dtypes)

(4, 3)
12
2
RangeIndex(start=0, stop=4, step=1)
Index(['city', 'data1', 'data2'], dtype='object')
[['서울' 491377 0.26217838985978775]
 ['대전' 568754 0.7752898197789083]
 ['대구' 758202 -0.17162504054135957]
 ['부산' 609924 1.1395903324545047]]
city      object
data1      int32
data2    float64
dtype: object

In [ ]:
df.head()       # 처음 5개 행
df.head(10)     # 처음 10개 행
df.tail()       # 마지막 5개 행
df.tail(3)      # 마지막 3개 행

print( df.info() )       # 전체 정보 (타입, 결측치 등)
df.describe()   # 기술통계 (수치형 컬럼만)

In [29]:
df.describe(include='all')
df.describe(include='object')
df.describe(include='int')
df.describe(include='float')

          data2
count  4.000000
mean   0.068274
std    1.079137
min   -1.215237
25%   -0.578595
50%    0.129972
75%    0.776840
max    1.228388

In [42]:
df[['city', 'data2']]
df['salary'] = [3000, 4000, 5000, 6000]
df['salary2'] = 0
df

  city   data1     data2  salary  salary2
0   서울  491377  0.262178    3000        0
1   대전  568754  0.775290    4000        0
2   대구  758202 -0.171625    5000        0
3   부산  609924  1.139590    6000        0

In [44]:
df.drop('salary2', axis=1)

  city   data1     data2  salary
0   서울  491377  0.262178    3000
1   대전  568754  0.775290    4000
2   대구  758202 -0.171625    5000
3   부산  609924  1.139590    6000

In [148]:
filepath = r'C:\SKN-29\Git\pandas\20260402.csv'
df = pd.read_csv(filepath)
df= pd.DataFrame(df)

# df.isnull().sum()
# df[ df.isna().any(axis=1) ].shape[0]
# df.describe()
df.info()

# df.rename(columns = {'소속 시장명(또는 상점가)' : '시장명-상점가'})


# years = list(map(int, df['등록년도'].unique()))
# for i in years:
#     print( f"{i} :{df[df['등록년도'] == i].shape[0]}" )



# df[['등록년도', '소재지', '취급품목']].value_counts()
pd.DataFrame( df[['등록년도', '소재지', '취급품목']].values )
# df['지류형 가맹 여부'].value_counts()
df[df['지류형 가맹 여부']=='N']
df.drop('등록년도', axis=1)
df.drop('등록년도', axis=1, inplace=True)
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150541 entries, 0 to 150540
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   가맹점명            150501 non-null  object
 1   소속 시장명(또는 상점가)  150541 non-null  object
 2   소재지             150541 non-null  object
 3   취급품목            150248 non-null  object
 4   지류형 가맹 여부       150541 non-null  object
 5   디지털형 가맹 여부      150541 non-null  object
 6   등록년도            150541 non-null  int64
dtypes: int64(1), object(6)
memory usage: 8.0+ MB

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y
...,...,...,...,...,...,...
150536,태성마트,단양구경시장(단양인정시장),충북,식잡,Y,Y
150537,동산닭집,단양구경시장(단양인정시장),충북,"일반한식,생닭",Y,Y
150538,파마미용실,단양구경시장(단양인정시장),충북,일반미용업,Y,Y
150539,두메하누,단양구경시장(단양인정시장),충북,한식점업,Y,Y
150540,단양보리밥,단양구경시장(단양인정시장),충북,분식,Y,Y

In [151]:
filepath = r'C:\SKN-29\Git\pandas\20260402.csv'
df = pd.read_csv(filepath)
df= pd.DataFrame(df)
df2 = df.head().copy()
df2

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025

In [153]:
df3 = df2.set_index('소재지').copy()
df3

,가맹점명,소속 시장명(또는 상점가),취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
소재지,,,,,,
경기,초마맨1981,권율 골목형상점가,짜장면 짬뽕 탕수육,Y,Y,2025
광주,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",꽈배기 도너츠,Y,Y,2025
광주,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",열쇠,Y,Y,2025
경기,참새 방앗간,권율 골목형상점가,육전 새우전,Y,Y,2025
광주,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",미용,Y,Y,2025

In [169]:
# df3.loc['광주','가맹점명':'취급품목']
df3.iloc[[1, 2, 4], 0:3]

        가맹점명                소속 시장명(또는 상점가)     취급품목
소재지
광주   못난이 꽈배기  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)  꽈배기 도너츠
광주    일곡열쇠철물  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)       열쇠
광주     뿔라헤어컷  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)       미용

In [181]:
sample_df1 = df.iloc[:5, :2]
sample_df2 = df.iloc[-5:, :2]
sample_df2

         가맹점명  소속 시장명(또는 상점가)
150536   태성마트  단양구경시장(단양인정시장)
150537   동산닭집  단양구경시장(단양인정시장)
150538  파마미용실  단양구경시장(단양인정시장)
150539   두메하누  단양구경시장(단양인정시장)
150540  단양보리밥  단양구경시장(단양인정시장)

In [195]:
sample_df3 = pd.concat([sample_df1, sample_df2], axis=0)
sample_df3

           가맹점명                소속 시장명(또는 상점가)
0       초마맨1981                     권율 골목형상점가
1       못난이 꽈배기  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
2        일곡열쇠철물  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
3        참새 방앗간                     권율 골목형상점가
4         뿔라헤어컷  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
150536     태성마트                단양구경시장(단양인정시장)
150537     동산닭집                단양구경시장(단양인정시장)
150538    파마미용실                단양구경시장(단양인정시장)
150539     두메하누                단양구경시장(단양인정시장)
150540    단양보리밥                단양구경시장(단양인정시장)

In [196]:
sample_df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 150540
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   가맹점명            10 non-null     object
 1   소속 시장명(또는 상점가)  10 non-null     object
dtypes: object(2)
memory usage: 240.0+ bytes

In [203]:
sample_df4 = sample_df3.reset_index()
sample_df4

    index     가맹점명                소속 시장명(또는 상점가)
0       0  초마맨1981                     권율 골목형상점가
1       1  못난이 꽈배기  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
2       2   일곡열쇠철물  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
3       3   참새 방앗간                     권율 골목형상점가
4       4    뿔라헤어컷  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
5  150536     태성마트                단양구경시장(단양인정시장)
6  150537     동산닭집                단양구경시장(단양인정시장)
7  150538    파마미용실                단양구경시장(단양인정시장)
8  150539     두메하누                단양구경시장(단양인정시장)
9  150540    단양보리밥                단양구경시장(단양인정시장)

In [ ]:
sample_df3.reset_index()
sample_df3.reset_index(drop=True)

      가맹점명                소속 시장명(또는 상점가)
0  초마맨1981                     권율 골목형상점가
1  못난이 꽈배기  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
2   일곡열쇠철물  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
3   참새 방앗간                     권율 골목형상점가
4    뿔라헤어컷  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
5     태성마트                단양구경시장(단양인정시장)
6     동산닭집                단양구경시장(단양인정시장)
7    파마미용실                단양구경시장(단양인정시장)
8     두메하누                단양구경시장(단양인정시장)
9    단양보리밥                단양구경시장(단양인정시장)

In [211]:
filepath = r'C:\SKN-29\Git\pandas\20260402.csv'
df = pd.read_csv(filepath)
df= pd.DataFrame(df)
df.head()
df.drop('가맹점명', axis=1)

,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025
...,...,...,...,...,...,...
150536,단양구경시장(단양인정시장),충북,식잡,Y,Y,2010
150537,단양구경시장(단양인정시장),충북,"일반한식,생닭",Y,Y,2010
150538,단양구경시장(단양인정시장),충북,일반미용업,Y,Y,2010
150539,단양구경시장(단양인정시장),충북,한식점업,Y,Y,2010
150540,단양구경시장(단양인정시장),충북,분식,Y,Y,2010

In [223]:
df['등록년도'].unique()
df[df['등록년도'].isin( [2020, 2025] )]

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025
...,...,...,...,...,...,...,...
96090,주식회사 하원,누웨마루거리상점가,제주,액세서리,Y,Y,2020
96091,네이처컬렉션,누웨마루거리상점가,제주,화장품,Y,Y,2020
96092,의정,누웨마루거리상점가,제주,한식,Y,Y,2020
96093,GS25연동중앙점,누웨마루거리상점가,제주,생필품,Y,Y,2020
96094,마코스포츠,서귀포중심상가,제주,의류및신발,Y,Y,2020